[package]
name = "bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
heck = "0.5.0"
wit-component = "0.227.1"
wit-parser = { version = "0.227.1", default-features = false }
