name: Deploy to GitHub Pages

on:
  #pull_request:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your node version

      - name: Install dependencies
        run: npm install # or yarn install or pnpm install

      - name: Build project
        run: npm run build # or yarn build or pnpm build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          single-commit: true
          folder: dist
